#include "engine/gameplay/GameplayAbilities.hpp"

#include <cmath>

namespace kb::gameplay {
bool GameplayAbilities::IsTargetAllowed(AbilityTargetRule rule, kb::scene::SceneEntity caster, GameplayIdentity casterIdentity, kb::scene::SceneEntity target, GameplayIdentity targetIdentity) const noexcept { if(!caster.IsValid()||!target.IsValid())return false; switch(rule){case AbilityTargetRule::Self:return caster==target; case AbilityTargetRule::Any:return true; case AbilityTargetRule::Friendly:return IsFriendly(casterIdentity,targetIdentity); case AbilityTargetRule::Hostile:return !IsFriendly(casterIdentity,targetIdentity);} return false; }
bool GameplayAbilities::Activate(const GameplayAbilityDefinition& definition, kb::scene::SceneEntity caster, GameplayIdentity casterIdentity, kb::scene::SceneEntity target, GameplayIdentity targetIdentity, GameplayModules& modules) { if(definition.id==0U||!std::isfinite(definition.cooldownSeconds)||definition.cooldownSeconds<0.0F||!std::isfinite(definition.cost)||definition.cost<0.0F||!std::isfinite(definition.effect.delta)||std::isnan(definition.durationSeconds)||definition.durationSeconds<0.0F||active_.contains(caster.Id())||!IsTargetAllowed(definition.targetRule,caster,casterIdentity,target,targetIdentity))return false; const auto cooldownOwner=cooldowns_.find(caster.Id()); if(cooldownOwner!=cooldowns_.end()){const auto cooldown=cooldownOwner->second.find(definition.id);if(cooldown!=cooldownOwner->second.end()&&cooldown->second>0.0F)return false;} if(definition.cost>0.0F){const auto resource=modules.Attribute(caster,definition.costAttribute);if(!resource.has_value()||resource->current<definition.cost)return false;} std::optional<AttributeState> effectState; if(definition.effect.attribute!=0U){effectState=modules.Attribute(target,definition.effect.attribute);if(!effectState.has_value())return false; effectState->current+=definition.effect.delta; if(!std::isfinite(effectState->current)||effectState->current<effectState->minimum||effectState->current>effectState->maximum)return false;} cooldowns_[caster.Id()].insert_or_assign(definition.id,0.0F); if(effectState.has_value()&&!modules.SetAttribute(target,definition.effect.attribute,*effectState))return false; if(definition.cost>0.0F&&!modules.SpendAttribute(caster,definition.costAttribute,definition.cost))return false; active_.emplace(caster.Id(),ActiveGameplayAbility{.id=definition.id,.caster=caster,.target=target,.remainingSeconds=definition.durationSeconds,.cooldownSeconds=definition.cooldownSeconds}); return true; }
// Activate reserves the cooldown slot, so ending an ability never allocates.
void GameplayAbilities::StartCooldown(kb::scene::SceneEntity::IdType caster, const ActiveGameplayAbility& ability, float elapsedAfterEnd) noexcept { const auto owner=cooldowns_.find(caster); if(owner==cooldowns_.end())return; const auto slot=owner->second.find(ability.id); if(slot!=owner->second.end())slot->second=ability.cooldownSeconds>elapsedAfterEnd?ability.cooldownSeconds-elapsedAfterEnd:0.0F; }
bool GameplayAbilities::End(kb::scene::SceneEntity::IdType caster, float elapsedAfterEnd) noexcept { const auto found=active_.find(caster); if(found==active_.end())return false; StartCooldown(caster,found->second,elapsedAfterEnd); active_.erase(found); return true; }
bool GameplayAbilities::Cancel(kb::scene::SceneEntity caster) noexcept { return End(caster.Id(),0.0F); }
bool GameplayAbilities::Complete(kb::scene::SceneEntity caster) noexcept { return End(caster.Id(),0.0F); }
void GameplayAbilities::Advance(float deltaSeconds) noexcept { if(!std::isfinite(deltaSeconds)||deltaSeconds<0.0F)return; for(auto& [owner,byAbility]:cooldowns_){(void)owner;for(auto& [ability,remaining]:byAbility){(void)ability;remaining=remaining>deltaSeconds?remaining-deltaSeconds:0.0F;}} for(auto ability=active_.begin();ability!=active_.end();){ActiveGameplayAbility& state=ability->second; if(state.remainingSeconds>deltaSeconds){state.remainingSeconds-=deltaSeconds;++ability;continue;} StartCooldown(ability->first,state,deltaSeconds-state.remainingSeconds); ability=active_.erase(ability);} }
bool GameplayAbilities::IsActive(kb::scene::SceneEntity caster) const noexcept { return active_.contains(caster.Id()); }
std::optional<ActiveGameplayAbility> GameplayAbilities::Active(kb::scene::SceneEntity caster) const noexcept { const auto found=active_.find(caster.Id()); return found==active_.end()?std::nullopt:std::optional<ActiveGameplayAbility>{found->second}; }
float GameplayAbilities::CooldownRemaining(kb::scene::SceneEntity caster, GameplayTagId ability) const noexcept { const auto owner=cooldowns_.find(caster.Id()); if(owner==cooldowns_.end())return 0.0F; const auto found=owner->second.find(ability); return found==owner->second.end()?0.0F:found->second; }
} // namespace kb::gameplay
