#include "engine/gameplay/GameplayAbilities.hpp"

#include <cmath>

namespace kb::gameplay {
bool GameplayAbilities::IsTargetAllowed(AbilityTargetRule rule, kb::scene::SceneEntity caster, GameplayIdentity casterIdentity, kb::scene::SceneEntity target, GameplayIdentity targetIdentity) const noexcept { if(!caster.IsValid()||!target.IsValid())return false; switch(rule){case AbilityTargetRule::Self:return caster==target; case AbilityTargetRule::Any:return true; case AbilityTargetRule::Friendly:return IsFriendly(casterIdentity,targetIdentity); case AbilityTargetRule::Hostile:return !IsFriendly(casterIdentity,targetIdentity);} return false; }
bool GameplayAbilities::Activate(const GameplayAbilityDefinition& definition, kb::scene::SceneEntity caster, GameplayIdentity casterIdentity, kb::scene::SceneEntity target, GameplayIdentity targetIdentity, GameplayModules& modules) { if(definition.id==0U||!std::isfinite(definition.cooldownSeconds)||definition.cooldownSeconds<0.0F||!std::isfinite(definition.cost)||definition.cost<0.0F||!std::isfinite(definition.effect.delta)||active_.contains(caster.Id())||!IsTargetAllowed(definition.targetRule,caster,casterIdentity,target,targetIdentity))return false; const auto cooldownOwner=cooldowns_.find(caster.Id()); if(cooldownOwner!=cooldowns_.end()){const auto cooldown=cooldownOwner->second.find(definition.id);if(cooldown!=cooldownOwner->second.end()&&cooldown->second>0.0F)return false;} if(definition.cost>0.0F){const auto resource=modules.Attribute(caster,definition.costAttribute);if(!resource.has_value()||resource->current<definition.cost)return false;} std::optional<AttributeState> effectState; if(definition.effect.attribute!=0U){effectState=modules.Attribute(target,definition.effect.attribute);if(!effectState.has_value())return false; effectState->current+=definition.effect.delta; if(!std::isfinite(effectState->current)||effectState->current<effectState->minimum||effectState->current>effectState->maximum)return false;} if(effectState.has_value()&&!modules.SetAttribute(target,definition.effect.attribute,*effectState))return false; if(definition.cost>0.0F&&!modules.SpendAttribute(caster,definition.costAttribute,definition.cost))return false; active_.emplace(caster.Id(),ActiveGameplayAbility{.id=definition.id,.caster=caster,.target=target}); cooldowns_[caster.Id()][definition.id]=definition.cooldownSeconds; return true; }
bool GameplayAbilities::Cancel(kb::scene::SceneEntity caster) noexcept { return active_.erase(caster.Id())!=0U; }
void GameplayAbilities::Advance(float deltaSeconds) noexcept { if(!std::isfinite(deltaSeconds)||deltaSeconds<0.0F)return; for(auto& [owner,byAbility]:cooldowns_){(void)owner;for(auto& [ability,remaining]:byAbility){(void)ability;remaining=remaining>deltaSeconds?remaining-deltaSeconds:0.0F;}} }
bool GameplayAbilities::IsActive(kb::scene::SceneEntity caster) const noexcept { return active_.contains(caster.Id()); }
} // namespace kb::gameplay
