#pragma once

#include "engine/assets/AssetId.hpp"
#include "engine/assets/AssetMetadata.hpp"

#include <cstdint>
#include <span>
#include <string_view>

namespace kb::assets {

// The engine's basic shapes, as Unreal ships /Engine/BasicShapes and Unity its built-in primitives:
// every project has them, under the same virtual path and the same asset id, without a file in the
// project. Sizes follow Unity's primitives (Plane 10 x 10 m), so scenes built in either engine match.
// The geometry is generated by the renderer (kb::render::BuiltInShapeMeshes); here live the names,
// ids and the small text source the cooker packs like any other asset source.
enum class BuiltInShape : std::uint8_t {
    Cube,     // 1 x 1 x 1 m
    Sphere,   // 1 m diameter
    Capsule,  // 2 m tall, 0.5 m radius, along Y
    Cylinder, // 2 m tall, 0.5 m radius, along Y
    Cone,     // 1 m tall, 0.5 m base radius, tip up
    Plane,    // 10 x 10 m on XZ, facing +Y
    Quad,     // 1 x 1 m on XY, facing -Z (toward a camera looking down +Z)
};

inline constexpr std::string_view kBuiltInShapeExtension = ".kbshape";

struct BuiltInShapeDesc {
    BuiltInShape shape;
    std::string_view name;        // "Plane"
    std::string_view virtualPath; // "/Engine/Shapes/Plane.kbshape"
    std::string_view source;      // the bytes the cooker snapshots as this asset's source
};

[[nodiscard]] std::span<const BuiltInShapeDesc> BuiltInShapes() noexcept;
// By name ("Plane"), virtual path with or without the extension ("/Engine/Shapes/Plane").
[[nodiscard]] const BuiltInShapeDesc* FindBuiltInShape(std::string_view nameOrPath) noexcept;
[[nodiscard]] const BuiltInShapeDesc* FindBuiltInShape(const AssetMetadata& metadata) noexcept;
[[nodiscard]] AssetId BuiltInShapeId(BuiltInShape shape) noexcept;
// Registry entry for a loose (not packaged) project: type RenderMesh, no physical file.
[[nodiscard]] AssetMetadata BuiltInShapeMetadata(const BuiltInShapeDesc& desc);

} // namespace kb::assets
