#include "script/ScriptFunctionDocumentation.hpp"

#include <array>

namespace kb::script {
namespace {

struct FunctionDocumentation {
    std::string_view name;
    std::string_view description;
};

constexpr auto kFunctionDocumentation = std::to_array<FunctionDocumentation>({
    { "Log", "Writes a UTF-8 message to the runtime log sink." },
    { "Input.IsPressed", "Returns whether the named input action is currently pressed for a local player." },
    { "Input.WasPressed", "Returns whether the named input action became pressed during the current frame." },
    { "Input.WasReleased", "Returns whether the named input action became released during the current frame." },
    { "Input.Value", "Reads the current scalar value of the named input action for a local player." },
    { "Input.Vector2", "Reads the current two-dimensional value of the named input action." },
    { "Input.Vector3", "Reads the current three-dimensional value of the named input action." },
    { "Input.AddMappingContext", "Activates an input mapping context for a local player at the requested priority." },
    { "Input.RemoveMappingContext", "Deactivates an input mapping context for a local player." },
    { "Input.Rebind", "Validates and applies a user key override to a live input mapping context." },
    { "Input.SaveRebindProfile", "Atomically saves one mapping context's user key overrides." },
    { "Input.LoadRebindProfile", "Loads user key overrides and applies them to the live mapping context." },
    { "Input.ActionBool", "Reads the normalized boolean value of an input action." },
    { "Input.ActionFloat", "Reads the normalized scalar value of an input action." },
    { "Input.Action2D", "Reads the normalized two-dimensional value of an input action." },
    { "Input.Pressed", "Reports whether an input action entered its pressed state this frame." },
    { "Input.Released", "Reports whether an input action entered its released state this frame." },
    { "Input.Held", "Reports whether an input action remains held in the current frame." },
    { "Pointer.Position", "Returns the pointer position in the active viewport." },
    { "Pointer.Delta", "Returns pointer movement accumulated during the current frame." },
    { "Pointer.Button", "Returns whether the requested pointer button is currently pressed." },
    { "Pointer.Scroll", "Returns normalized pointer-wheel detents accumulated during the current frame." },
    { "Pointer.Ray", "Builds a world-space ray through the pointer from the renderer-published active camera for a local player." },
    { "Input.PriorityGameplay", "Returns the canonical priority assigned to gameplay input contexts." },
    { "Input.PriorityUI", "Returns the canonical priority assigned to user-interface input contexts." },
    { "Input.PriorityConsole", "Returns the canonical priority assigned to console input contexts." },
    { "Input.PriorityDebugOverlay", "Returns the canonical priority assigned to debug-overlay input contexts." },
    { "Input.HasFocus", "Returns whether the game input surface currently owns input focus." },
    { "Input.IsGamepadConnected", "Returns whether the requested local gamepad is connected." },
    { "Input.HasHaptics", "Queries the haptic capabilities exposed by a local gamepad." },
    { "Input.SetVibration", "Sets low- and high-frequency vibration motors on a local gamepad." },
    { "Input.BindHapticsUser", "Routes a local user to a physical gamepad haptics slot." },
    { "Input.SetUserVibration", "Sets vibration through a local user's configured gamepad route." },
    { "Input.StopVibration", "Stops vibration on all local gamepads controlled by the runtime." },
    { "IsActionPressed", "Compatibility alias that returns whether an input action is currently pressed." },
    { "WasActionStarted", "Compatibility alias that reports an input action starting this frame." },
    { "WasActionTriggered", "Compatibility alias that reports an input action triggering this frame." },
    { "WasActionCompleted", "Compatibility alias that reports an input action completing this frame." },
    { "WasActionReleased", "Compatibility alias that reports an input action being released this frame." },
    { "GetActionValue", "Compatibility alias that reads a scalar input-action value." },
    { "GetActionValueXY", "Compatibility alias that reads a two-dimensional input-action value." },
    { "GetActionValueXYZ", "Compatibility alias that reads a three-dimensional input-action value." },
    { "AddMappingContext", "Compatibility alias that activates an input mapping context." },
    { "RemoveMappingContext", "Compatibility alias that deactivates an input mapping context." },

    { "Audio.Play", "Starts playback of an audio clip and returns the created runtime voice handle." },
    { "Audio.Stop", "Stops a runtime audio voice and releases its active playback state." },
    { "Audio.Pause", "Pauses playback of a runtime audio voice without resetting its position." },
    { "Audio.Resume", "Resumes playback of a paused runtime audio voice." },
    { "Audio.Seek", "Moves a runtime audio voice to the requested playback position." },
    { "Audio.SetVolume", "Sets the gain of a runtime audio voice." },
    { "Audio.SetPitch", "Sets the playback pitch of a runtime audio voice." },
    { "Audio.SetLoop", "Enables or disables looping for a runtime audio voice." },
    { "Audio.IsPlaying", "Returns whether a runtime audio voice is actively playing." },
    { "Audio.SetMixer", "Assigns the active audio mixer asset used by the scene." },
    { "Audio.ActiveMixer", "Returns the runtime identifier of the active audio mixer." },
    { "Audio.SetSnapshot", "Applies an audio mixer snapshot immediately." },
    { "Audio.ActiveSnapshot", "Returns the runtime identifier of the active mixer snapshot." },
    { "Audio.SetBusVolume", "Applies a runtime volume override to an audio mixer bus." },
    { "Audio.ClearBusVolume", "Removes the runtime volume override from an audio mixer bus." },
    { "Audio.TransitionToSnapshot", "Interpolates mixer state to an audio snapshot over a duration." },
    { "Audio.ConfigureOcclusion", "Configures physics-based audio occlusion for spatial voices." },
    { "Audio.OcclusionEnabled", "Returns whether physics-based audio occlusion is enabled." },
    { "Audio.GetPosition", "Returns the current playback position of a runtime audio voice." },
    { "Audio.AddMarker", "Adds a named playback marker to a runtime audio voice." },

    { "World.Current", "Returns the stable runtime identifier of the current world." },
    { "World.IsPlaying", "Returns whether the current world is executing Play Mode." },
    { "World.FrameIndex", "Returns the current rendered-frame index of the world." },
    { "World.FixedStepIndex", "Returns the current fixed-simulation step index of the world." },
    { "World.FindByName", "Finds the first live entity with the requested scene name." },
    { "World.Exists", "Returns whether an entity handle identifies a live entity in the current world." },
    { "World.IsActive", "Returns whether an entity is active in the current world." },
    { "World.SetActive", "Changes whether an entity participates in world updates." },
    { "World.IsPersistent", "Returns whether an entity survives active gameplay-scene replacement." },
    { "World.SetPersistent", "Changes whether an entity survives active gameplay-scene replacement." },
    { "World.Name", "Returns the scene name assigned to a live entity." },
    { "World.Spawn", "Queues creation of an entity or prefab instance with the requested pose and parent." },
    { "World.Destroy", "Destroys or queues destruction of an entity according to the requested ECS mode." },
    { "World.SetTag", "Adds or removes a gameplay tag on an entity." },
    { "World.HasTag", "Returns whether an entity has the requested gameplay tag." },
    { "World.FindByTag", "Finds the first live entity carrying the requested gameplay tag." },
    { "World.FindAllByTag", "Returns the next stable entity carrying a gameplay tag after a skip offset." },
    { "World.SetParent", "Changes an entity parent while preserving the scene hierarchy contract." },
    { "World.InstantiatePrefab", "Instantiates a registered prefab hierarchy with optional pose and parent overrides." },
    { "World.CreatePrefabParameters", "Creates a caller-owned, single-use atomic prefab parameter set." },
    { "World.SetPrefabParameterBool", "Adds a boolean component-property override to a prefab parameter set." },
    { "World.SetPrefabParameterInt", "Adds an integer component-property override to a prefab parameter set." },
    { "World.SetPrefabParameterFloat", "Adds a floating-point component-property override to a prefab parameter set." },
    { "World.SetPrefabParameterString", "Adds a string component-property override to a prefab parameter set." },
    { "World.SetPrefabParameterEntity", "Adds an entity-reference component-property override to a prefab parameter set." },
    { "World.SetPropertyBool", "Writes a script-exposed boolean component property on an entity." },
    { "World.SetPropertyInt", "Writes a script-exposed integer component property on an entity." },
    { "World.SetPropertyFloat", "Writes a script-exposed floating-point component property on an entity." },
    { "World.SetPropertyString", "Writes a script-exposed string component property on an entity." },
    { "World.SetPropertyEntity", "Writes a script-exposed entity-reference component property on an entity." },

    { "Time.Delta", "Returns scaled frame delta time in seconds." },
    { "Time.UnscaledDelta", "Returns frame delta time in seconds before time scaling." },
    { "Time.FixedDelta", "Returns the configured fixed-simulation step duration in seconds." },
    { "Time.Elapsed", "Returns scaled elapsed Play Mode time in seconds." },
    { "Time.FrameIndex", "Returns the current rendered-frame index." },
    { "Time.FixedStepIndex", "Returns the current fixed-simulation step index." },
    { "Time.Scale", "Returns the current gameplay time scale." },
    { "Time.SetScale", "Sets the gameplay time scale used by subsequent frame updates." },
    { "Timer.Once", "Creates a one-shot timer owned by an optional entity." },
    { "Timer.Repeat", "Creates a repeating timer owned by an optional entity." },
    { "Timer.Cancel", "Cancels a live timer idempotently." },
    { "Timer.Pause", "Pauses a live timer without discarding its remaining time." },
    { "Timer.Resume", "Resumes a paused live timer." },
    { "Timer.Creator", "Returns the entity that owns a live timer." },
    { "Task.WaitSeconds", "Starts a non-blocking task that completes after scaled scene time elapses." },
    { "Task.WaitFixedSteps", "Starts a task that completes after the requested number of real FixedTick steps." },
    { "Task.WaitEvent", "Starts a task that completes after the named runtime event reaches its observation stream." },
    { "Task.WaitAsset", "Starts a non-blocking observer task that completes when a registered asset enters the runtime cache." },
    { "Task.WaitScene", "Starts a non-blocking observer task that completes when the named scene content is loaded." },
    { "Events.EmitFiltered", "Synchronously emits a gameplay event to subscribers matching the optional entity, tag, component, loaded-scene, local-player, and channel filters." },
    { "Task.IsRunning", "Returns whether a runtime task is still pending or executing." },
    { "Task.Cancel", "Requests cancellation of a runtime task." },
    { "Task.Creator", "Returns the entity that owns a runtime task." },

    { "Physics.Raycast", "Casts a ray through the active physics world and returns the closest filtered hit." },
    { "Physics.AddForce", "Applies a continuous force to an entity rigid body." },
    { "Physics.AddImpulse", "Applies an instantaneous impulse to an entity rigid body." },
    { "Physics.SetVelocity", "Sets the linear velocity of an entity rigid body." },
    { "Physics.GetVelocity", "Reads the linear velocity of an entity rigid body." },
    { "Physics.SetAngularVelocity", "Sets the angular velocity of an entity rigid body." },
    { "Physics.GetAngularVelocity", "Reads the angular velocity of an entity rigid body." },
    { "Physics.Sleep", "Forces an entity rigid body into its sleeping state." },
    { "Physics.Wake", "Wakes an entity rigid body for physics simulation." },
    { "Physics.IsSleeping", "Returns whether an entity rigid body is sleeping." },
    { "Physics.MoveKinematic", "Moves a kinematic rigid body toward a target pose during the next simulation step." },
    { "Physics.SphereCast", "Sweeps a sphere through the physics world and returns the closest filtered hit." },
    { "Physics.BoxCast", "Sweeps an oriented box through the physics world and returns the closest filtered hit." },
    { "Physics.CapsuleCast", "Sweeps a capsule through the physics world and returns the closest filtered hit." },
    { "Physics.OverlapSphere", "Finds a filtered collider overlapping a sphere volume." },
    { "Physics.OverlapBox", "Finds a filtered collider overlapping an oriented box volume." },
    { "Physics.OverlapCapsule", "Finds a filtered collider overlapping a capsule volume." },
    { "Physics.ClosestPoint", "Returns the closest point on an entity collider to a world-space position." },
    { "Physics.LayerBit", "Returns the query-mask bit assigned to a named physics layer." },
    { "Physics.CharacterMove", "Moves a character controller using collision-aware character motion." },
    { "Physics.CharacterJump", "Requests a jump for a grounded character controller." },
    { "Physics.CharacterVelocity", "Reads the current velocity of a character controller." },
    { "Physics.CharacterIsGrounded", "Returns whether a character controller has a valid ground contact." },
    { "Physics.CharacterGroundNormal", "Returns the ground-contact normal of a character controller." },
    { "Physics.CharacterGroundVelocity", "Returns the velocity of the platform supporting a character controller." },
    { "Physics.SetDebugDrawEnabled", "Enables or disables physics debug geometry collection." },
    { "Physics.IsDebugDrawEnabled", "Returns whether physics debug geometry collection is enabled." },

    { "Transform.GetPosition", "Reads an entity world-space position." },
    { "Transform.SetPosition", "Sets an entity world-space position." },
    { "Transform.Translate", "Offsets an entity position by a world-space translation." },
    { "Transform.LocalPosition", "Reads an entity position relative to its parent." },
    { "Transform.SetLocalPosition", "Sets an entity position relative to its parent." },
    { "Transform.LocalRotation", "Reads an entity rotation relative to its parent." },
    { "Transform.SetLocalRotation", "Sets an entity rotation relative to its parent." },
    { "Transform.LocalScale", "Reads an entity scale relative to its parent." },
    { "Transform.SetLocalScale", "Sets an entity scale relative to its parent." },
    { "Transform.WorldPose", "Reads an entity world-space position, rotation, and scale." },
    { "Transform.SetWorldPose", "Sets an entity world-space position, rotation, and scale." },
    { "Transform.Parent", "Returns an entity parent handle, if one exists." },
    { "Transform.SetParent", "Changes an entity parent with explicit world-pose preservation." },
    { "Transform.ChildCount", "Returns the number of direct children of an entity." },
    { "Transform.GetChild", "Returns a direct child by stable hierarchy index." },
    { "Transform.FindChild", "Finds a direct child by its scene name." },
    { "Transform.Rotate", "Applies a quaternion rotation to an entity transform." },
    { "Transform.LookAt", "Rotates an entity to face a world-space target using an up direction." },
    { "Transform.TransformPoint", "Transforms a point from entity-local space to world space." },
    { "Transform.InverseTransformPoint", "Transforms a point from world space to entity-local space." },

    { "Math.Clamp", "Constrains a scalar value to an inclusive minimum and maximum." },
    { "Math.Lerp", "Linearly interpolates between two scalar values." },
    { "Math.InverseLerp", "Computes the interpolation parameter of a scalar within a range." },
    { "Math.Remap", "Maps a scalar from one numeric interval into another." },
    { "Math.SmoothStep", "Interpolates between two scalars with a cubic smooth-step curve." },
    { "Math.MoveTowards", "Moves a scalar toward a target without overshooting it." },
    { "Math.Damp", "Applies frame-rate-aware exponential damping toward a scalar target." },
    { "Math.Min", "Returns the smaller of two scalar values." },
    { "Math.Max", "Returns the larger of two scalar values." },
    { "Math.Abs", "Returns the absolute value of a scalar." },
    { "Math.Sign", "Returns the sign of a scalar as minus one, zero, or one." },
    { "Math.Floor", "Rounds a scalar down to the nearest integral value." },
    { "Math.Ceil", "Rounds a scalar up to the nearest integral value." },
    { "Math.Round", "Rounds a scalar to the nearest integral value." },
    { "Math.Frac", "Returns the fractional part of a scalar." },
    { "Math.Mod", "Returns the floating-point remainder of a division." },
    { "Math.Sqrt", "Returns the non-negative square root of a scalar." },
    { "Math.Pow", "Raises a scalar base to a scalar exponent." },
    { "Math.Exp", "Returns the natural exponential of a scalar." },
    { "Math.Log", "Returns the natural logarithm of a positive scalar." },
    { "Math.Sin", "Returns the sine of an angle expressed in radians." },
    { "Math.Cos", "Returns the cosine of an angle expressed in radians." },
    { "Math.Tan", "Returns the tangent of an angle expressed in radians." },
    { "Math.Asin", "Returns the principal arcsine in radians for an input in the valid domain." },
    { "Math.Acos", "Returns the principal arccosine in radians for an input in the valid domain." },
    { "Math.Atan", "Returns the principal arctangent of a scalar in radians." },
    { "Math.Atan2", "Returns the quadrant-aware angle of a two-dimensional direction in radians." },
    { "Math.Dot", "Returns the dot product of two three-dimensional vectors." },
    { "Math.Cross", "Returns the cross product of two three-dimensional vectors." },
    { "Math.Length", "Returns the Euclidean length of a three-dimensional vector." },
    { "Math.Normalize", "Returns a unit-length vector and reports whether normalization was valid." },
    { "Math.Distance", "Returns the Euclidean distance between two three-dimensional points." },
    { "Math.Project", "Projects a three-dimensional vector onto another vector." },
    { "Math.Reflect", "Reflects an incident vector about a surface normal." },
    { "Math.Refract", "Refracts an incident vector through a surface using a refraction ratio." },
    { "Math.Angle", "Returns the unsigned angle between two vectors in radians." },
    { "Math.SignedAngle", "Returns the oriented angle between two vectors around an axis in radians." },
    { "Math.Slerp", "Spherically interpolates between two quaternions." },
    { "Math.LookRotation", "Builds a quaternion that faces a direction while respecting an up vector." },
    { "Math.FromToRotation", "Builds the shortest quaternion rotating one direction onto another." },
    { "Math.RotateTowards", "Rotates one quaternion toward another by a bounded angular step." },
    { "Math.Random01", "Returns a deterministic pseudo-random scalar in the unit interval for a seed and sequence." },
    { "Math.Noise1D", "Evaluates deterministic seeded gradient noise in one dimension." },
    { "Math.Noise2D", "Evaluates deterministic seeded gradient noise in two dimensions." },
    { "Math.Noise3D", "Evaluates deterministic seeded gradient noise in three dimensions." },
    { "Math.RandomSeed", "Creates a deterministic random-stream state from a seed." },
    { "Math.RandomNextUInt32", "Advances a deterministic random stream and returns an unsigned integer sample." },
    { "Math.RandomNextFloat01", "Advances a deterministic random stream and returns a unit-interval scalar sample." },
    { "Math.RandomRange", "Advances a deterministic random stream and samples a floating-point range." },
    { "Math.RandomRangeInt", "Advances a deterministic random stream and samples an integer range." },
    { "Math.Ease", "Evaluates the selected allocation-free easing curve at a normalized parameter." },
    { "Math.RectContains", "Returns whether a two-dimensional point lies inside a rectangle." },
    { "Math.RectIntersects", "Returns whether two rectangles overlap." },
    { "Math.PlaneSignedDistance", "Returns the signed distance from a point to a plane." },
    { "Math.RayPointAt", "Returns a point at a distance along a ray." },
    { "Math.RayPlaneIntersect", "Computes the forward intersection of a ray and a plane." },
    { "Math.IVec2Add", "Adds two two-dimensional integer vectors." },
    { "Math.IVec2ManhattanDistance", "Returns Manhattan distance between two integer grid coordinates." },

    { "Scene.Load", "Starts loading a scene by its runtime scene identifier." },
    { "Scene.Unload", "Unloads a loaded scene by its runtime scene identifier." },
    { "Scene.SetActive", "Makes a loaded scene the active gameplay scene." },
    { "Scene.GetActive", "Returns the runtime identifier of the active gameplay scene." },
    { "Scene.Find", "Resolves a registered scene name to its runtime scene identifier." },
    { "Scene.LoadProgress", "Returns the current load state and normalized progress of a scene." },

    { "MeshRenderer.SetMesh", "Assigns a registered mesh asset to an entity mesh renderer." },
    { "MeshRenderer.SetMaterial", "Assigns a registered material asset to every mesh section on an entity." },
    { "MeshRenderer.SetMaterialSlot", "Assigns a registered material asset to one mesh section." },
    { "MeshRenderer.GetMaterialSlot", "Returns the material asset assigned to one mesh section." },
    { "MeshRenderer.ClearMaterialSlot", "Removes the material override from one mesh section." },
    { "MeshRenderer.SetMaterialInstance", "Assigns a live material-instance handle to one mesh section." },
    { "MeshRenderer.ClearMaterialInstance", "Removes the live material-instance override from one mesh section." },
    { "MaterialInstance.Create", "Creates a runtime material instance from a registered parent material." },
    { "MaterialInstance.Release", "Releases ownership of a runtime material instance." },
    { "MaterialInstance.Exists", "Returns whether a runtime material-instance handle is live." },
    { "MaterialInstance.Parent", "Returns the registered parent material of a runtime material instance." },
    { "MaterialInstance.SetParameterScalar", "Sets a validated scalar parameter override on a runtime material instance." },
    { "MaterialInstance.SetParameterBool", "Sets a validated boolean parameter override on a runtime material instance." },
    { "MaterialInstance.ClearParameter", "Removes a named parameter override from a runtime material instance." },
    { "PostProcess.SetProfile", "Assigns a registered post-process profile to the current scene." },
    { "PostProcess.ClearProfile", "Clears the current scene post-process profile." },
    { "PostProcess.ActiveProfile", "Returns the registered post-process profile active in the current scene." },
    { "Particles.Create", "Creates a runtime particle-system instance from a registered asset." },
    { "Particles.Release", "Releases ownership of a runtime particle-system instance." },
    { "Particles.Exists", "Returns whether a runtime particle-system handle is live." },
    { "Particles.Play", "Starts emission and simulation for a runtime particle-system instance." },
    { "Particles.Stop", "Stops emission for a runtime particle-system instance." },
    { "Particles.IsPlaying", "Returns whether a runtime particle-system instance is emitting." },
    { "Particles.SetSeed", "Sets the deterministic random seed of a runtime particle-system instance." },
    { "Particles.SetParameterScalar", "Sets a scalar parameter override on a runtime particle-system instance." },
    { "Particles.ClearParameter", "Removes a named parameter override from a runtime particle-system instance." },
    { "Particles.Emit", "Emits an explicit number of particles from a runtime instance." },
    { "Particles.LiveCount", "Returns the number of live particles in a runtime instance." },
    { "Animator.Play", "Immediately selects and seeks a named animator state." },
    { "Animator.CrossFade", "Transitions from the active animator state to another named state." },
    { "Animator.SetSpeed", "Sets the finite non-negative playback speed of an attached animator." },
    { "Animator.Speed", "Returns the playback speed of an attached animator." },
    { "Animator.SetBool", "Sets a boolean parameter declared by the attached animator controller." },
    { "Animator.SetInt", "Sets an integer parameter declared by the attached animator controller." },
    { "Animator.SetFloat", "Sets a finite float parameter declared by the attached animator controller." },
    { "Animator.SetTrigger", "Sets a trigger parameter declared by the attached animator controller." },
    { "Animator.ResetTrigger", "Clears a trigger parameter declared by the attached animator controller." },
    { "Animator.SetIKTarget", "Sets a named world-space IK/rig target consumed by constraints in the attached controller." },
    { "Animator.ClearIKTarget", "Clears a named IK/rig target from the attached animator runtime." },
    { "Animator.State", "Returns the active state, normalized time, and transition state of an animator layer." },
    { "Timeline.Create", "Creates a scene-owned timeline instance from a typed timeline asset and owner." },
    { "UI.Create", "Queues creation of a UI element under a live UI document element." },
    { "UI.Destroy", "Queues destruction of a non-root UI element and its descendants." },
    { "UI.Show", "Queues visibility of a live UI element." },
    { "UI.Hide", "Queues hiding of a live UI element." },
    { "UI.Focus", "Moves keyboard/gamepad focus to a visible focusable UI element and emits UI.Focus hooks." },
    { "Localization.SetCatalog", "Selects a typed localization catalog asset and resets the active language to its authored fallback." },
    { "Localization.SetLanguage", "Selects an authored language from the active localization catalog." },
    { "Localization.Language", "Returns the active localization language." },
    { "Localization.Translate", "Resolves an authored localization key, falling back to the catalog fallback language." },
    { "Localization.FormatPlural", "Formats an authored plural localization key with the supplied count." },
    { "UI.Find", "Setup-only O(n) lookup of one uniquely named UI element; cache the returned handle for hot paths." },
    { "UI.SetText", "Queues text for a Text, Button, or InputField UI element." },
    { "UI.SetImage", "Queues an image asset reference for an Image UI element." },
    { "UI.SetToggle", "Queues the selected value of a Toggle UI element." },
    { "UI.SetSlider", "Queues the value and optional range of a Slider UI element." },
    { "UI.ListAppend", "Queues one non-empty item at the end of a List UI element." },
    { "UI.ListClear", "Queues removal of all items from a List UI element." },
    { "UI.ConfigureList", "Configures a bounded virtual-list pool; scrolling rebinds slots without creating UI elements." },
    { "UI.ListScrollTo", "Queues a virtual List viewport index; out-of-range indices clamp to the retained item range." },
    { "UI.SetScrollOffset", "Queues a non-negative scroll offset for a ScrollView UI element." },
    { "UI.SetModalOpen", "Queues the open state of a ModalDialog UI element." },
    { "UI.EmitClick", "Queues a UI.Click event with pointer coordinates for a visible UI element." },
    { "UI.EmitPointer", "Queues a UI.Pointer event with pointer coordinates for a visible UI element." },
    { "UI.EmitSubmit", "Queues a UI.Submit event with submitted text for a visible UI element." },
    { "UI.EmitChanged", "Queues a UI.Changed event with a numeric value for a visible UI element." },
    { "UI.EmitFocus", "Queues a UI.Focus event with the focused state for a visible UI element." },
    { "UI.EmitNavigation", "Queues a UI.Navigation event with a validated navigation direction." },
    { "Timeline.Release", "Releases a timeline instance and its resolved bindings." },
    { "Timeline.Play", "Starts or resumes a timeline before its authored end." },
    { "Timeline.Pause", "Pauses a timeline without changing its playhead." },
    { "Timeline.Seek", "Scrubs to an absolute time and applies the pose without emitting markers." },
    { "Timeline.Skip", "Skips forward with explicit crossed-marker emission or suppression semantics." },
    { "Timeline.Bind", "Overrides one declared timeline binding with a live scene entity." },
    { "Timeline.IsPlaying", "Returns whether a timeline instance is advancing." },
    { "Timeline.Time", "Returns a timeline instance's current absolute time." },

    { "Renderer.IsVisible", "Returns whether an entity was visible in the selected completed render frame." },
    { "Renderer.GetBounds", "Returns the world-space render bounds published for an entity." },
    { "Renderer.TestFrustum", "Tests world-space bounds against a selected viewport frustum." },
    { "Renderer.HasFrame", "Returns whether renderer query data exists for the selected completed frame." },
    { "Renderer.WorldToScreen", "Projects a world-space point into a selected viewport." },
    { "Renderer.ScreenPointToRay", "Builds a world-space picking ray from a selected viewport coordinate." },
    { "Renderer.ScreenToWorld", "Unprojects a viewport coordinate and depth into world space." },
    { "Renderer.CaptureScreen", "Queues an asynchronous screen capture and returns its runtime handle." },
    { "Renderer.CaptureStatus", "Returns the current state of an asynchronous screen capture." },

    { "Assets.Find", "Resolves a virtual asset path to a stable runtime asset reference." },
    { "Assets.FindTyped", "Resolves a virtual asset path and validates the requested asset kind." },
    { "Assets.KindOf", "Returns the registered kind of an asset reference." },
    { "Assets.IsLoaded", "Returns whether an asset reference currently has a loaded payload." },
    { "Assets.Load", "Loads an asset payload synchronously and acquires a shared runtime reference." },
    { "Assets.LoadAsync", "Starts non-blocking asset loading and returns a runtime task handle." },
    { "Assets.Unload", "Releases one runtime reference to a loaded asset." },
    { "Assets.RefCount", "Returns the runtime reference count held for an asset." },
    { "Assets.SetUnloadPolicy", "Sets the runtime unload policy for an asset." },
    { "Assets.UnloadPolicy", "Returns the runtime unload policy configured for an asset." },
    { "Assets.PruneUnreferenced", "Unloads eligible asset payloads that have no runtime references." },
    { "Assets.Validate", "Validates that an asset reference is live and optionally has the expected kind." },
    { "Assets.GetProperty", "Reads a script-exposed property from a loaded asset payload." },

    { "Save.SetBool", "Stores a boolean in the active save-game document." },
    { "Save.SetInt", "Stores an integer in the active save-game document." },
    { "Save.SetFloat", "Stores a floating-point value in the active save-game document." },
    { "Save.SetString", "Stores a UTF-8 string in the active save-game document." },
    { "Save.GetBool", "Reads a boolean from the active save-game document." },
    { "Save.GetInt", "Reads an integer from the active save-game document." },
    { "Save.GetFloat", "Reads a floating-point value from the active save-game document." },
    { "Save.GetString", "Reads a UTF-8 string from the active save-game document." },
    { "Save.Has", "Returns whether the active save-game document contains a key." },
    { "Save.Remove", "Removes a key from the active save-game document." },
    { "Save.Clear", "Removes all values from the active save-game document." },
    { "Save.Write", "Serializes the active save-game document to its configured persistent slot." },
    { "Save.Read", "Loads the configured persistent slot into the active save-game document." },
    { "Save.SetAsset", "Stores a stable asset reference in the active save-game document." },
    { "Save.GetAsset", "Reads a stable asset reference from the active save-game document." },
    { "Settings.SetBool", "Stores a boolean in the user-settings document." },
    { "Settings.SetInt", "Stores an integer in the user-settings document." },
    { "Settings.SetFloat", "Stores a floating-point value in the user-settings document." },
    { "Settings.SetString", "Stores a UTF-8 string in the user-settings document." },
    { "Settings.GetBool", "Reads a boolean from the user-settings document." },
    { "Settings.GetInt", "Reads an integer from the user-settings document." },
    { "Settings.GetFloat", "Reads a floating-point value from the user-settings document." },
    { "Settings.GetString", "Reads a UTF-8 string from the user-settings document." },
    { "Settings.Has", "Returns whether the user-settings document contains a key." },
    { "Settings.Remove", "Removes a key from the user-settings document." },
    { "Settings.Clear", "Removes all values from the user-settings document." },
    { "Settings.Write", "Serializes user settings to their configured persistent storage." },
    { "Settings.Read", "Loads user settings from their configured persistent storage." },
    { "Settings.SetAsset", "Stores a stable asset reference in the user-settings document." },
    { "Settings.GetAsset", "Reads a stable asset reference from the user-settings document." },

    { "Array.Create", "Creates an owned script array with a validated element type." },
    { "Array.Length", "Returns the number of elements in a script array." },
    { "Array.Push", "Appends an element to a script array." },
    { "Array.Get", "Reads an element from a script array by index." },
    { "Array.Set", "Replaces an element in a script array by index." },
    { "Array.RemoveAt", "Removes an element from a script array by index." },
    { "Array.Clear", "Removes all elements from a script array." },
    { "Set.Create", "Creates an owned script set with a validated element type." },
    { "Set.Count", "Returns the number of unique values in a script set." },
    { "Set.Add", "Inserts a value into a script set." },
    { "Set.Contains", "Returns whether a script set contains a value." },
    { "Set.Remove", "Removes a value from a script set." },
    { "Set.Clear", "Removes all values from a script set." },
    { "Map.Create", "Creates an owned script map with validated key and value types." },
    { "Map.Count", "Returns the number of key-value pairs in a script map." },
    { "Map.Set", "Inserts or replaces a key-value pair in a script map." },
    { "Map.Get", "Reads the value associated with a key in a script map." },
    { "Map.ContainsKey", "Returns whether a script map contains a key." },
    { "Map.Remove", "Removes a key-value pair from a script map." },
    { "Map.Clear", "Removes all key-value pairs from a script map." },
    { "Queue.Create", "Creates an owned first-in-first-out script queue." },
    { "Queue.Count", "Returns the number of values in a script queue." },
    { "Queue.Enqueue", "Appends a value to the back of a script queue." },
    { "Queue.Dequeue", "Removes and returns the oldest value in a script queue." },
    { "Queue.Peek", "Returns the oldest value in a script queue without removing it." },
    { "Queue.Clear", "Removes all values from a script queue." },
    { "Stack.Create", "Creates an owned last-in-first-out script stack." },
    { "Stack.Count", "Returns the number of values in a script stack." },
    { "Stack.Push", "Pushes a value onto a script stack." },
    { "Stack.Pop", "Removes and returns the newest value in a script stack." },
    { "Stack.Top", "Returns the newest value in a script stack without removing it." },
    { "Stack.Clear", "Removes all values from a script stack." },

    { "Text.ParseInt", "Parses a signed integer from invariant-culture UTF-8 text." },
    { "Text.ParseUInt", "Parses an unsigned integer from invariant-culture UTF-8 text." },
    { "Text.ParseFloat", "Parses a floating-point value from invariant-culture UTF-8 text." },
    { "Text.IsGuid", "Validates the canonical textual representation of a GUID." },
    { "Text.ParseColor", "Parses a color from the documented invariant text formats." },
    { "Text.ParseDate", "Parses a date from the documented invariant calendar format." },
});

} // namespace

std::string_view BuiltInScriptFunctionDescription(std::string_view canonicalName) noexcept {
    for (const FunctionDocumentation& documentation : kFunctionDocumentation) {
        if (documentation.name == canonicalName) {
            return documentation.description;
        }
    }
    return {};
}

} // namespace kb::script
